### ISSUE TITLE
Wayland Support

### ISSUE THREAD

**Issue by dal00** [farfalleflickan/desktop-tux#1]
More and more desktops are going towards default Wayland desktops.
It would be a good idea to take that into account early.
So unless the goal is to learn xlib you should maybe use a toolkit to support both X11 and Wayland.

**Comment by farfalleflickan** [comment]
Unfortunately I do think that Wayland has still quite a lot of issues to iron out before mainstream adoption, so "future proofing" this code by rewriting it for Wayland would be quite useless and a lot of work for nothing. 
Besides, there are a number of hurdles:
* AFAIK, unless you want to delve deep into OpenGL and hijacking other windows drawing calls and so on, this is the *only* way to implement an overlay ( which, at it's core, is what this program is )
* backwards compatibility
* portability, this code should be able to run on basically any version Xorg version ( at least anything from 2004 )

You would have a point if Wayland was mature enough and if this code didn't work with Wayland, which it does (at least in my tests with Sway ).
